name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Extract version
        id: extractversion
        run: |
          curl https://archive.physionet.org/physiotools/wfdb.tar.gz | tar xvz
          VERSION=$(basename wfdb-* | cut -c 6-)
          echo ::set-output name=version::${VERSION}
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: matjazmav
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push the Docker image
        uses: docker/build-push-action@v2.0.1
        with:
          tags: |
            matjazmav/wfdb:latest
            matjazmav/wfdb:${{ steps.extractversion.outputs.version }}
      
